# Generated by Django 3.2.5 on 2021-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='libera',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
