# Generated by Django 3.2.5 on 2021-08-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tvshow_libera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='libera',
            field=models.DateTimeField(null=True),
        ),
    ]
