# Generated by Django 3.2.5 on 2021-08-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tvshow_libera'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='libera',
            field=models.DateField(null=True),
        ),
    ]
